version: "3.9"

services:
    backend:
        build:
            context: ./backend
        restart: always
        ports: 
            - "8000:8000"
        volumes: 
            - ./backend/:/usr/src/app/
        env_file: 
            - .env
    # frontend:
    #     build:
    #         context: ./frontend
    #     restart: always
    #     depends_on:
    #         - backend
    #     volumes: 
    #         - ./frontend/:/usr/src/app/
    #     ports: 
    #         - "4200:4200"
